services:
  - type: web
    name: golden-heart-orphanage
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static
    startCommand: node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_VERSION
        value: 20
